### PR TITLE
Download dependencies in Circle ahead of build time

### PR DESCRIPTION
**Pull request by danielcompton**
I'm not 100% sure why, but mvn dependency:go-offline does not download
all of the necessary dependencies to run the build. This means that
Circle's caching isn't very effective, as more deps are downloaded after
the cache is saved.
- [ ] Downloads the necessary plugins ahead of time, should dramatically speed up build time.
- [x] I also needed to update the location for central. See
  http://stackoverflow.com/questions/35022961/how-do-i-use-mvn-dependencyget-to-use-https-repo1-maven-org/35023015#35023015
  for more details.

### CODE REVIEW

**Comment by arrdem** [comment]
dde44d5d7192098ecbf80376c2074401be453875f2138ad936f5cdae0e2ef32a

**Comment by danielcompton** [comment]
Nope. It's actually slower :( The startup time on `mvn dependencies:get` is dominating. I think I'll need to figure out why not all of the projects are being downloaded from `mvn dependencies:go-offline`.

**Comment by arrdem** [comment]
I found [this](https://medium.com/@keithkml/speeding-up-a-maven-build-on-circleci-a40eba351ff1#.1dpe15261) floating around which suggests

``` yaml
dependencies:
  override:
    ....
    - mvn --fail-never dependency:go-offline || true
```

**Comment by arrdem** [comment]
Ok. So for posterity, my comment doesn't solve the particular issue. What's going in is it seems that there are implicit plugins or something else, which aren't being resolved during the instance of `$ mvn dependency:go-offline` that CircleCI already runs.

**Comment by arrdem** [comment]
So I mucked with just manually specifying the implicit plugins, and got some discouraging warnings about duplicate plugin specifications so I didn't chase that any further.

The fix I did come up with was to simply use `ant`, which doesn't share the odd plugin behavior of `mvn` and seems to play very nicely with CircleCI's dependency caching. I also rebased on top of `develop`.

The downside of this approach is that it's unclear how to deploy from `ant`, not that I was able to beat `mvn` into submission on that point with a reasonable effort.

**Comment by danielcompton** [comment]
Not totally fond of abandoning maven, but it is pretty annoying trying to figure this out.

**Comment by arrdem** [comment]
I'll dink with this some more in a minute.

**Comment by arrdem** [comment]
So with these last two patches and both running this test script and running on CircleCI I can't seem to stop the build step pulling stuff down. No idea what's going on here. https://www.refheap.com/114280

**Pull request merged**
